### ISSUE TITLE
为何有些配置的站点无法出现结果

### ISSUE THREAD

**Issue by Crucialer** [dubox/jSearch#11]
https://www.ncbi.nlm.nih.gov/clinvar/
这是我想配置的一个站点，但是没有结果。请问哪里出现了问题？

**Comment by dubox** [comment]
![image](https://user-images.githubusercontent.com/8044162/54739527-72670100-4bf3-11e9-94e5-9a720b20ae4b.png)
可以搜到的。

搜不到可能有以下几种情况：
**1.搜索引擎没有收录；**
插件提供了三种引擎可以都试一下看哪个搜的多一些，如果都没有就没办法了；
**2.没有搜索词的情况：**
没有输入搜索词的时候，插件默认搜索该站点基于所选搜索引擎所收录的最近1天的内容，所以如果站点1天内没有新内容或新内容没有被搜索引擎收录则也是没有结果的；
**3.谷歌人机验证：**
我们使用谷歌基本都要翻墙，有些翻墙软件会自动匹配不同国家的服务器做代理，这种情况有时候谷歌会说你网络不稳定，要做人机验证，这种情况可以打开 www.google.com 看看能不能正常打开（这个后面插件也会加入检测功能）

总之本插件的所有搜索都是基于搜索引擎的，搜索引擎没有收录的话肯定是搜不到的；
还有 SEO 不友好的站点也是不适合用本插件的，比如：
![image](https://user-images.githubusercontent.com/8044162/54740689-11d9c300-4bf7-11e9-822e-f6cbe46401d9.png)
^这种的
或者需要登录才能看的内容；

（本条就当 FAQ 了）

**Comment by Crucialer** [comment]
你好，我想再请教下，就是相对自己添加的站点进行精确搜索怎么设置？
![image](https://user-images.githubusercontent.com/40562250/56859970-0b8ff100-69c4-11e9-871c-9dd13058a129.png)
上图是我想精确搜索的一个站点：https://www.ncbi.nlm.nih.gov/clinvar/。
下面是我用jSearch得到的结果：
![image](https://user-images.githubusercontent.com/40562250/56860020-675a7a00-69c4-11e9-9364-433a2c9bc5ec.png)
然后下图是我在原站点搜索得到的精确结果：
![image](https://user-images.githubusercontent.com/40562250/56860046-a1c41700-69c4-11e9-98b7-180699a691c4.png)

**Comment by dubox** [comment]
> 你好，我想再请教下，就是相对自己添加的站点进行精确搜索怎么设置？
> ![image](https://user-images.githubusercontent.com/40562250/56859970-0b8ff100-69c4-11e9-871c-9dd13058a129.png)
> 上图是我想精确搜索的一个站点：[https://www.ncbi.nlm.nih.gov/clinvar/。](https://www.ncbi.nlm.nih.gov/clinvar/%E3%80%82)
> 下面是我用jSearch得到的结果：
> ![image](https://user-images.githubusercontent.com/40562250/56860020-675a7a00-69c4-11e9-9364-433a2c9bc5ec.png)
> 然后下图是我在原站点搜索得到的精确结果：
> ![image](https://user-images.githubusercontent.com/40562250/56860046-a1c41700-69c4-11e9-98b7-180699a691c4.png)

jSearch 是基于百度、谷歌等搜索引擎的，而搜索引擎的逻辑是先要收录，没收录的内容就搜不到，所以要非常精确的搜索几乎不可能

**Comment by Crucialer** [comment]
请问作者是否可以帮忙实现精确搜索的功能呢？有偿。

**Comment by dubox** [comment]
> 请问作者是否可以帮忙实现精确搜索的功能呢？有偿。

QQ 2231974273
