### ISSUE TITLE
希望支持搜索接口分组

### ISSUE THREAD

**Issue by putigeekli** [dubox/jSearch#13]
希望支持搜索接口分组，让用户可自定义搜索特定细分类目的网址资料。
例如：产品经理需要搜索查看很多细分类目，如产品、营销、运营、数据报告等网址的资料。产品经理需要搜索查看很多资料，假设现在需要搜索查看一批营销网址里，关键词为“定位”文章，他只需勾选“营销”类目的分组，就可以批量搜索这些“营销”网址里的特定关键词的内容了。可以自定义搜索。

**Comment by dubox** [comment]
好建议！

**Comment by dubox** [comment]
v1.3.0
