### ISSUE TITLE
后台显示出错

### ISSUE THREAD

**Issue by beming** [dubox/jSearch#15]
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
上下文
_generated_background_page.html
堆叠追踪
_generated_background_page.html:0 (匿名函数)
这里没有任何通知，往前走吧。

Unchecked runtime.lastError: The message port closed before a response was received.
上下文
_generated_background_page.html
堆叠追踪
_generated_background_page.html:0 (匿名函数)
这里没有任何通知，往前走吧。

**Comment by dubox** [comment]
这个应该不影响使用，下个版本会捎带处理一下，感谢反馈

**Comment by dubox** [comment]
v1.2.2
