### ISSUE TITLE
【bug】打开搜索结果后搜索框无法出现

### ISSUE THREAD

**Issue by horizon98** [dubox/jSearch#19]
如题。如果打开了某个搜索结果（即在新的标签页中打开了某个搜索结果），再返回jSearch的界面，搜索框会消失。
若打开搜索条自动隐藏，则鼠标移动到该位置无法弹出；若关闭自动隐藏，则搜索条位置失踪。
chrome 版本： 78.0.3904.87

另外不知道作者可不可以考虑这个界面样式，感觉保留原来的搜索界面挺好的，这样切换也方便：[https://github.com/h2y/allso](https://github.com/h2y/allso)
测试界面：[http://h2y.github.io/allso/#123](http://h2y.github.io/allso/#123)

感谢作者的开发这么棒的项目！

**Comment by horizon98** [comment]
补充一下chrome版本信息：
chrome 版本  78.0.3904.87

**Comment by dubox** [comment]
我这测试是好的，你用的什么操作系统 什么浏览器，最好能有截图；
然后allso这个项目也挺不错的，但是和jSearch 不一样的逻辑，而且已经有了allso 我再搞一个一样的就没有意义了；
也感谢你关注jSearch

**Comment by horizon98** [comment]
win10 1903，chrome 正式版 78.0.3904.87。
附件中是录屏，第一段是直接左键直接在前台打开，第二段是鼠标中键在后台打开，打开搜索结果后，大概过了1~2秒，搜索框就没了。
[录屏.zip](https://github.com/dubox/jSearch/files/3802950/default.zip)

插件设置见下图。
![image_317](https://user-images.githubusercontent.com/48114360/68105074-5876f600-ff18-11e9-9586-80334c0625a2.png)

chrome在拓展程序页面显示该程序有错误，见下图。
![image_319](https://user-images.githubusercontent.com/48114360/68105288-fc60a180-ff18-11e9-8a30-07107ec932d9.png)

关闭其它所有插件后结果依然一样，麻烦作者了。开发者模式安装的插件好像无法在隐私窗口中使用，因此没法儿测试。

**Comment by dubox** [comment]
测试了一下 确实有这个问题   我会尽快修复的，暂时可以先用快捷搜索框
