### ISSUE TITLE
想点击最顶上记录时，顶部搜索框总是会误展现，比较影响使用

### ISSUE THREAD

**Issue by xwzpp** [dubox/jSearch#2]
最顶上的记录总是会触发顶部搜索框的误展示，能否加个配置，关掉这个顶部搜索框，只使用快捷键呼出

**Comment by dubox** [comment]
但是打开设置面板的按钮在上面，关了就打不开设置了，我想一下看这个该怎么优化。
感谢你的建议。

**Comment by dubox** [comment]
v0.6.0 已解决此问题，感谢建议，觉得好用的话记得给个 star 啊 哈哈哈。。。
