### ISSUE TITLE
希望可以添加一个快捷键打开/关闭jSearch的默认搜索引擎

### ISSUE THREAD

**Issue by starry925** [dubox/jSearch#20]
扩展依然保持打开，不过可以添加快捷键来关闭/打开搜索引擎默认为jsearch的问题，有时候并不需要利用此扩展搜索众多网站，那样会添加过多时间来搜索一个小问题，浏览器扩展自带的快捷键设置只能与一般情况下左键点击扩展图标一样激活jsearch的github二维码（如下图），
![image](https://user-images.githubusercontent.com/52288410/69057943-9cf0ae80-0a4d-11ea-8d9c-635f05fdebaf.png)
当我实施这个快捷键后只会和普通的点击扩展图标一样
![image](https://user-images.githubusercontent.com/52288410/69057374-b2b1a400-0a4c-11ea-960c-811a617faf1a.png)
希望添加一个快捷键设置选项就如下面这张图的扩展快捷键设置一样
![image](https://user-images.githubusercontent.com/52288410/69057491-f5737c00-0a4c-11ea-8fc4-365a13d3c533.png)
可以在不关闭此扩展的情况下用快捷键开启/关闭扩展其中的某项功能
也就是关闭jseach的搜索引擎。
![image](https://user-images.githubusercontent.com/52288410/69058207-315b1100-0a4e-11ea-879c-2a9980eea220.png)

**Comment by dubox** [comment]
这个可以考虑；
但是那个二维码不是github的二维码，是当前页面的二维码，为了方便你用手机访问的，看来大家都没有认真看介绍啊😂

**Comment by starry925** [comment]
jsearch扩展会默认将百度和Google的搜索引擎结果默认导向至jsearch的搜索引擎chrome-extension://kincdamgkecgeknoeedgdckeajdlamfb/options/search.html?#{搜索内容}，有时候只是想随便在百度或Google搜索都必须先打开其官网再在其搜索框输入和搜索，就会很麻烦，此占用问题目前只能通过关闭此扩展才能正常简单搜索，但是浏览器想再打开jsearch就又得必须扩展管理页面或者另一个扩展管理程序找到它再打开就会很麻烦😓所以希望作者能像上述说的加个快捷键关闭jsearch的功能，解决之后可有偿回报🤭用了好久的聚搜，搭配Quicker一起使用简直不要太爽！这回复效率杠杠滴！作者也可以试试Quicker这款软件哦，推荐一下~~~

**Comment by starry925** [comment]
二维码其实没必要了,,,有点鸡肋，因为有同类扩展或浏览器自带功能可以做到的东西，咱搜索引擎平时都隐藏图标的，根本就用不到到这个功能，可能是当初作者没啥新奇的点子但自己又有需求才加上的吧?🤭

**Comment by dubox** [comment]
你真会猜，就是我的需求怎样😎
Quicker 貌似是win上的 ，mac上有spotlight
有偿回报就不用了，指望开源项目发家致富到下辈子了😂，有空了关注下公众号就行😂

**Comment by starry925** [comment]
早已关注了~~~哈哈

**Comment by dubox** [comment]
v1.3.0

**Comment by starry925** [comment]
360扩展传一下😘

**Comment by dubox** [comment]
> 360扩展传一下😘

已经上传了，等审核
