### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by webxmsj** [dubox/jSearch#26]
1. 期待配置站点支持删除(更加灵活)
2. 列表支持拖拽排列，灵活的自定义布局格式

**Comment by dubox** [comment]
这两个功能都有了
排序：见[v0.3.1](https://github.com/dubox/jSearch/releases/tag/v0.3.1)，需要关掉“自然排序”
删除：见[v1.2.3](https://github.com/dubox/jSearch/releases/tag/v1.2.3)
