### ISSUE TITLE
快捷键可否自己定义？

### ISSUE THREAD

**Issue by SmallTeddy** [dubox/jSearch#27]
当前空格键会在页面翻页，不会弹出搜索框
j键与visium 冲突
Ctrl j 在chrome中会弹出下载
tab和esc均没有反应

**Comment by dubox** [comment]
你是啥系统啊，刚试了下  ，几个快捷键在win10和mac上都是好的（空格确实会在个别网站失灵）；
tab和esc 只能退出搜索框  不能唤醒；
自定义快捷键  可以考虑，有空了加上。

**Comment by SmallTeddy** [comment]
谢谢  最近有点忙  才看到  我的都是win10的电脑  外星人笔记本  应该不会是硬件的问题  chrome浏览器都是翻墙下的  自动更新最新版本的  是不是可能chrome版本太新了  产生的一些兼容问题呢？ 谁知道呢  哈哈

**Comment by dubox** [comment]
好了 可以自定义了
