### ISSUE TITLE
请问Chrome网上应用店有吗？我没有找到

### ISSUE THREAD

**Issue by wayne0926** [dubox/jSearch#28]
我没有搜索到jsearch在chrome商店，如果真的没有的话建议上传！（包括Edge外接程序市场），谢谢

**Comment by wayne0926** [comment]
如果使用开发模式来使用有很大的不方便，而且每次启动都会提示，让人很烦（虽然有方式解决），但是直接安装商店里的就更方便了

**Comment by dubox** [comment]
这个没办法，因为不合规上传不了。。。
话说你的解决方式是啥？

**Comment by wayne0926** [comment]
> 这个没办法，因为不合规上传不了。。。
> 话说你的解决方式是啥？

我就是直接下载放进去的。关于弹关闭开发者模式我之前看到过，你可以百度一下。（我现在没用）
