### ISSUE TITLE
无法正常使用！！！

### ISSUE THREAD

**Issue by HuangChao5** [dubox/jSearch#32]

**Comment by HuangChao5** [comment]
google的开发者模式下报错：

'content_security_policy': Ignored insecure CSP value "'unsafe-inline'" in directive 'script-src'.

**Comment by dubox** [comment]
我这没有这个情况，你的浏览器版本和操作系统是多少？

**Comment by HuangChao5** [comment]
> 我这没有这个情况，你的浏览器版本和操作系统是多少？

谷歌版本 89.0.4389.90（正式版本） （64 位）
操作版本  win10专业版64位

**Comment by HuangChao5** [comment]
11
