### ISSUE TITLE
增加结果中搜索以及部分网站添加后无法显示搜索结果

### ISSUE THREAD

**Issue by daaicong** [dubox/jSearch#33]
1、能否增加结果中搜索，以缩小搜索范围。以下是结果中搜索的案例简介：
问：在cnki数据库文献查询中，“在结果中检索”和“检索文献”有什么区别呢?
答：就是说比如你搜索了“苹果”这个单词，会出来很多的结果，这个结果会很大，如果你想在这个检索结果中搜索某个更小范围的话，那就输入关键词后点“在结果中检索”这样就是在刚才检索的“苹果”中继续缩小范围，如果用“检索文献”的话则就是重新从总库里搜索，第二次搜索的关键词和“苹果”是没有关系的。

2、部分网站添加后无法显示搜索结果。
例如https://tool.farbun.com/，https://metaso.cn/#/，这两个网站放入后jsearch，进行检索得不到任何结果。

3、如果用的是百度引擎，例如添加4个网站，可能得到的搜索结果只有2个，但必应引擎就有4个。

**Comment by dubox** [comment]
1.结果中搜索没法加
2.这两个网站都是需要登录的，搜索引擎收录不了
3.百度目前出现了屏蔽的情况

**Comment by daaicong** [comment]
您好，还有一个问题，我每次使用插件时，电脑总会很快出现网络故障，网络会变得很慢，甚至打不开网页，需要等一段时间才能打开网页，不知道如何解决这个问题。

**Comment by daaicong** [comment]
您好，还有一个问题，我每次使用插件时，电脑总会很快出现网络故障，网络会变得很慢，甚至打不开网页，需要等一段时间才能打开网页，不知道如何解决这个问题。

**Comment by daaicong** [comment]
您好，还有一个问题，我每次使用插件时，电脑总会很快出现网络故障，网络会变得很慢，甚至打不开网页，需要等一段时间才能打开网页，不知道如何解决这个问题。

**Comment by daaicong** [comment]
此外，对于前几天的问题2，好像不是登录的问题，因为知乎也需要登录的，我自己用其他需要登录的网站也是可以的。

**Comment by dubox** [comment]
> 您好，还有一个问题，我每次使用插件时，电脑总会很快出现网络故障，网络会变得很慢，甚至打不开网页，需要等一段时间才能打开网页，不知道如何解决这个问题。

这个情况我没有遇到，也没有别的用户反馈这个问题，你看看是不是其他原因

**Comment by dubox** [comment]
> 此外，对于前几天的问题2，好像不是登录的问题，因为知乎也需要登录的，我自己用其他需要登录的网站也是可以的。

知乎不需要登录也能看到帖子内容的，总之百度或者其他搜索引擎收录了的内容才能搜索。

**Comment by daaicong** [comment]
1、我自己觉得网络出现故障，可能是用jsearch时被怀疑是机器人搜索或者攻击，代理服务器或者运营商把网络屏蔽了，导致dns解析不了，或者域名故障，不知有无解决方法。
2、关于打开jsearch快捷键的问题，我看之前也有网友反馈过，可否考虑，设置一个jsearch快捷键，按快捷键即可搜索，但不出现二维码，要想出现二维码，可以在设置里面单独设置，二维码对您可能有较大用处，但对于部分使用者而言，搜索时还需要再点击一次二维码，比较影响使用体验。

**Comment by dubox** [comment]
1.你的网络环境是不是比较特殊，一般的宽带应该没有这个限制
2.有快捷键的，在设置里面，项目主页也有说明

**Comment by daaicong** [comment]
好的，可能是我网络环境的问题，能否考虑改善下二维码的设置问题。

**Comment by dubox** [comment]
> 好的，可能是我网络环境的问题，能否考虑改善下二维码的设置问题。

二维码不影响使用啊，你可以快捷键搜索，也可以直接在地址栏搜索
