### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by 7polo** [dubox/jSearch#7]
很不错的作品的， 关于个人的几点建议， 能否增加几个配置项：
1. 配置是否隐藏搜索栏
2. 显示列数的配置
谢谢

**Comment by dubox** [comment]
先感谢您的支持！！！
1.搜索栏 你是想让它可以一直显示么？
2.列的话 每一列都可以控制是否显示， 所以算是包含了列数控制的。

**Comment by 7polo** [comment]
感谢回复， 搜索栏：希望这个能加个配置项，控制显示还是隐藏

**Comment by dubox** [comment]
v1.1.1 已解决
