### ISSUE TITLE
配置的站点可否支持删除

### ISSUE THREAD

**Issue by 273539918** [dubox/jSearch#8]
目前只有新增功能，可否删除（强迫症）

**Comment by dubox** [comment]
哈哈，最开始是有这个计划的，后来有了修改和开关功能就感觉删除不是强需求了 所以就搁置了，这个可以考虑下个版本捎带加上；感谢支持！！🤓

**Comment by dubox** [comment]
v1.2.3 已经支持，来的有点晚  但还是来了
